/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model109N(props) {
  
  const { nodes, materials } = useGLTF('/109N.glb')

  for (const key in materials) {
    const material = materials[key]
    material.transparent = true
    material.opacity = 0.4
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_other_rect0.geometry}
        material={nodes.table_other_rect0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_dining_four_back_arms0.geometry}
        material={nodes.chair_dining_four_back_arms0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_other_rect1.geometry}
        material={nodes.table_other_rect1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_other_rect2.geometry}
        material={nodes.table_other_rect2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.storage_cabinet_low10.geometry}
        material={nodes.storage_cabinet_low10.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_other_rect3.geometry}
        material={nodes.table_other_rect3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_swivel_star_back_arms0.geometry}
        material={nodes.chair_swivel_star_back_arms0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_swivel_star_back_arms1.geometry}
        material={nodes.chair_swivel_star_back_arms1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_swivel_star_back_arms2.geometry}
        material={nodes.chair_swivel_star_back_arms2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_swivel_star_back_no0.geometry}
        material={nodes.chair_swivel_star_back_no0.material}
      />
      {Array.from({ length: 14 }, (_, i) => i + 1).map((i) => (
        <mesh
          key={`wall_${i}`}
          castShadow
          receiveShadow
          geometry={nodes[`wall_${i}`].geometry}
          material={nodes[`wall_${i}`].material}
          material-color={props.color}
        />
      ))}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.joint_0.geometry}
        material={nodes.joint_0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.joint_1.geometry}
        material={nodes.joint_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.joint_2.geometry}
        material={nodes.joint_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.joint_3.geometry}
        material={nodes.joint_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.joint_4.geometry}
        material={nodes.joint_4.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.joint_5.geometry}
        material={nodes.joint_5.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door_0.geometry}
        material={nodes.door_0.material}
        material-color={props.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.door_2.geometry}
        material={nodes.door_2.material}
        material-color={props.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window_0.geometry}
        material={nodes.window_0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window_2.geometry}
        material={nodes.window_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_Dining_Room.geometry}
        material={nodes.floor_Dining_Room.material}
        material-color={props.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_Dining_Room_2.geometry}
        material={nodes.floor_Dining_Room_2.material}
        material-color={props.color}
      />
    </group>
  )
}

useGLTF.preload('/109N.glb')